import { Link } from '@tanstack/react-router';
import { useRef } from 'react';
import { ArrowRight, ArrowUpRight, ArrowLeft, Phone, MapPin, Clock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { restaurant } from '@/data/restaurant';
import facade from '@/assets/restaurant/DEVANT.png.asset.json';
import room from '@/assets/restaurant/INTERIEUR.png.asset.json';
import gambas from '@/assets/restaurant/GAMBAS.png.asset.json';
import meat from '@/assets/restaurant/VIANDE.png.asset.json';
import wine from '@/assets/restaurant/VIN.png.asset.json';
import tartare from '@/assets/restaurant/TARTARE.png.asset.json';
import fish from '@/assets/restaurant/POISSON.png.asset.json';
export function Hero() { return <section className="hero" aria-label="La Chaumière, restaurant français à Poissy"><img className="hero-photo" src={facade.url} alt="La façade et la terrasse de La Chaumière, 6 Rue au Pain à Poissy" width={768} height={1034} fetchPriority="high"/><div className="hero-content"><p className="eyebrow">RESTAURANT FRANÇAIS · POISSY</p><h1>La Chaumière</h1><p className="hero-subtitle">Une cuisine française généreuse,<br/>faite maison et pleine de saveurs.</p><div className="hero-actions"><Button asChild variant="hero"><a href={restaurant.phoneHref}>Réserver une table <ArrowUpRight/></a></Button><Button asChild variant="heroOutline"><Link to="/la-carte">Découvrir la carte <ArrowRight/></Link></Button></div></div><div className="hero-bottom"><a href={restaurant.mapsUrl} target="_blank" rel="noopener noreferrer"><span className="hero-stars">★</span>4,4/5 · 594 avis Google</a><a href="#introduction" className="hero-scroll" aria-label="Découvrir La Chaumière">DÉCOUVRIR</a></div></section>; }
export function Introduction() { return <section id="introduction" className="section reveal"><div className="container intro-grid"><div className="intro-copy"><p className="eyebrow section-kicker">L’ESPRIT LA CHAUMIÈRE</p><h2>Une adresse gourmande<br/>au cœur de Poissy</h2><p>Une cuisine française faite maison, des saveurs soignées et le plaisir de vous accueillir. À La Chaumière, la générosité se retrouve dans l’assiette comme dans le service.</p><p>Un déjeuner, un dîner, un moment à partager : laissez-vous conseiller selon vos envies.</p><Button asChild variant="editorial"><Link to="/le-restaurant">Le restaurant <ArrowRight/></Link></Button></div><div className="intro-photo"><div className="photo-wrap h-full"><img src={room.url} alt="La salle de La Chaumière, ses banquettes et ses tables dressées" loading="lazy" width={768} height={1019}/></div><div className="photo-caption">Cuisine française · Fait maison · Poissy</div></div></div></section>; }
export function SignatureDishes() { const dishes=[{type:'Les saveurs de la maison',name:'Les gambas',category:'À découvrir à notre table',image:gambas.url,alt:'Une assiette de gambas photographiée à La Chaumière'},{type:'Le plaisir du plat',name:'Tartare de bœuf',category:'Frites / salade',image:tartare.url,alt:'Le tartare de bœuf de La Chaumière accompagné de frites et de salade'},{type:'La cuisine généreuse',name:'Côté viande',category:'Les plaisirs d’une cuisine française',image:meat.url,alt:'Une assiette de viande et de pommes de terre servie à La Chaumière'}]; return <section className="section menu-preview reveal"><div className="container"><div className="section-topline"><div><p className="eyebrow section-kicker">LE GOÛT DU FAIT MAISON</p><h2>À la carte</h2><p>Les saveurs de La Chaumière</p></div><Button asChild variant="editorial"><Link to="/la-carte">Découvrir la carte <ArrowRight/></Link></Button></div><div className="dish-grid">{dishes.map(d=><article className="dish" key={d.name}><Link to="/la-carte" aria-label={`Découvrir la carte : ${d.name}`}><div className="photo-wrap dish-image"><img src={d.image} alt={d.alt} width={768} height={966} loading="lazy"/></div><p className="dish-type">{d.type}</p><h3>{d.name}</h3><p className="dish-note">{d.category}</p></Link></article>)}</div><p className="image-notice">Les plats proposés peuvent évoluer selon la carte et les disponibilités.</p></div></section>; }
export function Experience() { return <section className="section experience reveal"><div className="container"><div className="experience-header"><p className="eyebrow section-kicker">LE PLAISIR D’ÊTRE À TABLE</p><h2>Bien plus qu’un repas</h2><p>Un accueil chaleureux, une équipe attentive et une cuisine maison. Au déjeuner comme au dîner, le plaisir d’un moment simple et savoureux.</p></div><div className="experience-grid"><div className="photo-wrap"><img src={room.url} width={768} height={1019} alt="Les tables et les banquettes de La Chaumière" loading="lazy"/></div><div className="photo-wrap"><img src={fish.url} width={768} height={966} alt="Une assiette de poisson servie à La Chaumière" loading="lazy"/></div><div className="photo-wrap"><img src={wine.url} width={768} height={1027} alt="Un verre de vin rouge servi à La Chaumière" loading="lazy"/></div></div></div></section>; }
const reviews=[{title:'Un repas surprenant en saveurs',quote:'« Adresse à ne pas manquer à Poissy. Un service impeccable qui sait conseiller ses clients selon leurs envies, pour un repas surprenant en saveurs et agréable au palais. Le fait maison est mis en avant et cela se ressent dans les plats. »',author:'Tony · Avis client fourni',stars:true},{title:'Un accueil qui fait la différence',quote:'Accueil chaleureux, service attentionné et conseils selon les envies : des qualités mises en avant par les clients.',author:'Synthèse des retours clients',stars:false},{title:'Le goût des bons moments',quote:'Une atmosphère agréable et une cuisine française de qualité, appréciées au déjeuner comme au dîner.',author:'Synthèse des retours clients',stars:false}];
export function Reviews() { const track=useRef<HTMLDivElement>(null); const move=(direction:number)=>{const el=track.current;if(!el)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;el.scrollBy({left:direction*(el.clientWidth/2+14),behavior:reduced?'instant':'smooth'});};return <section className="section reviews reveal"><div className="container"><div className="reviews-heading"><div><p className="eyebrow section-kicker">VOS MOMENTS, VOS MOTS</p><h2>Ils se sont régalés</h2></div><div className="rating"><div className="rating-number">4,4 <span>/ 5</span></div><div><div className="stars" aria-label="Note Google : 4,4 sur 5">★★★★★</div><p className="rating-detail">594 avis Google</p></div></div></div><div className="review-track" ref={track} aria-label="Retours clients" tabIndex={0}>{reviews.map(r=><article className="review-card" key={r.title}>{r.stars?<div className="stars" aria-label="5 étoiles">★★★★★</div>:<p className="eyebrow section-kicker">{r.title}</p>}<blockquote>{r.quote}</blockquote><p className="review-author">— {r.author}</p></article>)}</div><div className="review-controls"><Button asChild variant="editorial"><a href={restaurant.mapsUrl} target="_blank" rel="noopener noreferrer">Voir les avis sur Google <ArrowUpRight/></a></Button><div className="flex gap-2"><Button variant="ghost" size="icon" className="review-arrow" aria-label="Avis précédents" onClick={()=>move(-1)}><ArrowLeft/></Button><Button variant="ghost" size="icon" className="review-arrow" aria-label="Avis suivants" onClick={()=>move(1)}><ArrowRight/></Button></div></div></div></section>; }
export function Reservation() { return <section className="reservation"><p className="eyebrow mb-5">À BIENTÔT À LA CHAUMIÈRE</p><h2>Une table vous attend</h2><p>Pour déjeuner, dîner ou simplement découvrir La Chaumière, réservez votre table.</p><Button asChild variant="hero"><a href={restaurant.phoneHref}><Phone/> Réserver par téléphone</a></Button><div className="reservation-phone"><a href={restaurant.phoneHref}>{restaurant.phone}</a></div></section>; }
export function OpeningHours() { return <div className="hours"><h3>Nos services</h3><p>{restaurant.hours.lunch}</p><p>{restaurant.hours.dinner}</p>{restaurant.hours.verifiedDays&&<p>{restaurant.hours.verifiedDays}</p>}<p className="hours-note">Pour connaître les jours d’ouverture et confirmer les horaires, contactez-nous par téléphone.</p></div>; }
export function Contact() { const key=import.meta.env['VITE_LOVABLE_CONNECTOR_GOOGLE_MAPS_BROWSER_KEY']; return <section className="section reveal"><div className="container contact-grid"><div className="contact-info"><p className="eyebrow section-kicker">RENDEZ-VOUS À POISSY</p><h2>Venez nous retrouver</h2><div className="contact-row"><MapPin/><div><strong>LA CHAUMIÈRE</strong><address>6 Rue au Pain<br/>78300 Poissy</address><Button asChild variant="editorial"><a href={restaurant.directionsUrl} target="_blank" rel="noopener noreferrer">Itinéraire <ArrowUpRight/></a></Button></div></div><div className="contact-row"><Phone/><a href={restaurant.phoneHref}>{restaurant.phone}</a></div><div className="contact-row"><Clock/><div>{restaurant.priceRange}<br/><span className="text-muted-foreground text-xs">Sur place · Sans vente à emporter ni livraison<br/>Un accueil ouvert à toutes et à tous · LGBTQ+ friendly</span></div></div><OpeningHours/></div>{key?<iframe className="map-frame" title="Localisation de La Chaumière à Poissy" src={`https://www.google.com/maps/embed/v1/place?key=${key}&q=${encodeURIComponent('La Chaumière 6 Rue au Pain 78300 Poissy')}`} loading="lazy" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:<div className="map-panel"><div><MapPin size={34} strokeWidth={1}/><p className="eyebrow mt-5">AU CŒUR DE POISSY</p><h3>6, rue au Pain</h3><p>78300 Poissy, France</p><Button asChild variant="restaurant"><a href={restaurant.mapsUrl} target="_blank" rel="noopener noreferrer">Ouvrir Google Maps <ArrowUpRight/></a></Button></div></div>}</div></section>; }
