import { Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Menu, X, Phone, ArrowUpRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { restaurant } from '@/data/restaurant';
const links = [{to:'/',label:'Accueil'},{to:'/la-carte',label:'La Carte'},{to:'/le-restaurant',label:'Le Restaurant'},{to:'/avis',label:'Avis'},{to:'/contact',label:'Contact'}] as const;
export function Header() {
 const [open,setOpen] = useState(false);
 useEffect(()=> { if (!open) return; const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);}; const previous=document.body.style.overflow; document.body.style.overflow='hidden'; document.addEventListener('keydown',onKey); return ()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',onKey);}; },[open]);
 return <><a className="skip-link" href="#contenu">Aller au contenu</a><header className="site-header"><div className="nav-inner"><Link to="/" className="wordmark" onClick={()=>setOpen(false)}>LA CHAUMIÈRE</Link><nav className="nav-links" aria-label="Navigation principale">{links.map(l=><Link key={l.to} to={l.to} className="nav-link" activeOptions={{exact:true}}>{l.label}</Link>)}</nav><Button asChild variant="restaurant" className="desktop-booking"><a href={restaurant.phoneHref}>Réserver une table <ArrowUpRight/></a></Button><Button variant="ghost" size="icon" className="mobile-toggle" aria-label={open?'Fermer le menu':'Ouvrir le menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div></header>{open&&<nav id="mobile-menu" className="mobile-menu" aria-label="Navigation mobile">{links.map(l=><Link key={l.to} to={l.to} onClick={()=>setOpen(false)}>{l.label}</Link>)}<Button asChild variant="restaurant"><a href={restaurant.phoneHref}><Phone/> Réserver une table</a></Button></nav>}</>;
}
export function Footer() { return <><footer className="footer"><div className="container"><div className="footer-main"><div><Link to="/" className="footer-brand">LA CHAUMIÈRE</Link><p className="footer-address">6 Rue au Pain · 78300 Poissy<br/><a href={restaurant.phoneHref}>{restaurant.phone}</a></p></div><nav className="footer-nav" aria-label="Navigation de pied de page">{links.map(l=><Link key={l.to} to={l.to}>{l.label}</Link>)}</nav></div><div className="footer-bottom"><span>© La Chaumière — Poissy</span><div className="footer-legal"><Link to="/mentions-legales">Mentions légales</Link><Link to="/politique-de-confidentialite">Politique de confidentialité</Link></div></div></div></footer><a className="mobile-call" href={restaurant.phoneHref}><Phone/> Réserver · {restaurant.phone}</a></>; }
