name: Sync to Client Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Client Repo
        run: |
          git remote add client https://x-access-token:${{ secrets.CLIENT_GITHUB_TOKEN }}@github.com/Lillah2003/chaumiere-cuisine-site.git
          git push --force client main
