name: Sync to Client Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CLIENT_SSH_KEY }}
          known_hosts: ignore

      - name: Push to Client Repo
        run: |
          git remote add client git@github.com:Lillah2003/chaumiere-site.git
          git push --force client main
